### ISSUE TITLE
Enter custom HEX code

### ISSUE THREAD

**Issue by kyellareddy** [superhighfives/pika#107] opened 2023-09-27 22:38 UTC
There should be a way for me to enter a custom HEX code for either a foreground or background color and get a list of all the colors that go with that color I entered.

**Comment by superhighfives** [comment] 2023-09-29 10:44
Thanks for flagging this issue. It looks like a duplicate of https://github.com/superhighfives/pika/issues/57, so going to close in favour of that.

**Closed by superhighfives** 2023-09-29 10:44 UTC
Labels: enhancement
