### ISSUE TITLE
Automatically copy picked color to clipboard

### ISSUE THREAD

**Issue by kjbotka** [superhighfives/pika#67] opened 2021-07-23 18:44 UTC
It would be amazing if we had the option to automatically copy the picked color to the clipboard when I pick a color. This would save the step of having to copy and I could directly pick and color and immediately paste the hex code.

**Comment by superhighfives** [comment] 2021-07-26 11:06
Thanks for flagging—as this is a duplicate of #64, going to close this in favour of that one.

**Closed by superhighfives** 2021-07-26 11:06 UTC
Labels: enhancement
