### ISSUE TITLE
Pika icon displays when connecting to an external display

### ISSUE THREAD

**Issue by gitatmax** [superhighfives/pika#99] opened 2023-04-17 10:17 UTC
**Describe the bug**
When using an external display, even with the Pika toolbar icon disabled, the icon will sometimes appear to the left of the external monitor until the app is force-quit & re-opened

**To Reproduce**
1. Disable the toolbar icon
2. Connect to an external display
3. The icon should appear after some time or a restart

**Expected behavior**
The icon shouldn't ever appear anywhere

**Screenshots**
I will grab a screenshot to post here when I see it next.

**Environment (please complete the following information):**
 - OS: macOS
 - App Version: 0.0.15 (build 34)
 - Architecture: Apple Silicon

**Comment by superhighfives** [comment] 2023-04-27 15:34
Ugh, that's not great. It sounds like a bug in macOS, given that the current implementation is using `.isVisible` to show and hide it.

I can try and recreate it, but is there anything you've noticed that might be triggering it? For example, plugging into or disconnecting the external display? There may be an event I can hook into to ensure it's reflecting the right visibility.

Thanks for flagging, too, @gitatmax. 👍

**Comment by jacob-shuman** [comment] 2023-06-01 18:25
I'm having the same issue as well, I believe the issue may be caused when connecting to an external display. Not sure if it's relevant but I have 2 external monitors connected and it looks like it's showing on the monitor on the left which happens to be the primary display.

I am using macos ventura 13.3.1

Please let me know if theres anything else i can help with!

*(I love Pika, thank you so much for all the time and effort that goes into working on it)*

![Screenshot 2023-06-01 at 2 16 17 pm](https://github.com/superhighfives/pika/assets/44483276/11a23d3f-989a-4e4e-88bb-10af76e35559)

**Comment by jacob-shuman** [comment] 2023-06-02 14:08
> Thanks for sharing the additional context, @jacob-shuman, and for the kind words.
> 
> 
> 
> Out of curiousity, does this happen with any other apps you're using?

Not that I've noticed no. I've only ever see it happen with Pika in recent memory.

**Comment by arthurflor23** [comment] 2023-08-15 10:21
Hi,

Same problem here. It happens when I connect closed mac to an external monitor, and the temporary solution is to completely close and reopen the app.
Also, it only happens with the Pika app in "Hide menu bar icon" checked.

**Comment by jhil** [comment] 2023-10-01 22:32
Another repro here, sharing my comment from another issue: https://github.com/superhighfives/pika/issues/108#issuecomment-1742223111

**Comment by superhighfives** [comment] 2023-10-02 10:25
Thanks for all the feedback on this one, everyone. Added to my milestone for the 0.0.16 release, which I'm planning on getting started on (along with #109, etc).

**Comment by superhighfives** [comment] 2023-10-11 13:25
Finally getting around to taking a look at this bug, and I'm struggling to reproduce it. Out of curiosity, which laptop are you using? Does it have a notch? Thanks so much for reporting!

**Comment by superhighfives** [comment] 2023-10-11 16:21
Whoa, plot twist, happened on my external display (with a notch-y MB). 

<img width="224" alt="Screenshot 2023-10-11 at 17 20 31" src="https://github.com/superhighfives/pika/assets/449385/7b9c8c16-5682-45ac-94ca-cace75ab2fbf">

Now to work out what on earth is going on there. 😅

**Comment by bikrrr** [comment] 2023-12-03 19:32
Oops! I must have missed this before submitting issue #108, as it seems to be the same problem. The latest update should fix it.

Can everyone here update to **Pika 0.0.16** and report back if it's still an issue?

**Comment by jacob-shuman** [comment] 2023-12-20 19:26
> Finally getting around to taking a look at this bug, and I'm struggling to reproduce it. Out of curiosity, which laptop are you using? Does it have a notch? Thanks so much for reporting!

I haven't updated to the latest version yet but I can confirm this was happening on my 2019 macbook pro (connected to 2 external monitors) without a notch.

**Comment by bikrrr** [comment] 2023-12-20 19:45
@jacob-shuman Please let us know if it still happens for you with 0.0.16. Thanks! 🙏

**Comment by jacob-shuman** [comment] 2023-12-21 15:20
Looks like 0.0.16 fixed it for me 🚀

this is what I tried:

- enable hide menu icon from menu bar option in settings
- quit pika
- open pika from command bar (icon shows up in top left corner overlapping the apple icon button in the menu bar)
- update to 0.0.16
- quit pika
- open pika from command bar (no overlapping icon 👍🏻)
- open pika from command bar again to put window in foreground
- reboot mac
- icon still doesnt show up
- ...profit?

Thank you for the fix, I really appreciate the work that went into getting this resolved!

**Comment by superhighfives** [comment] 2023-12-21 17:24
All credit goes to @bikrrr for his awesome work on this. Thank you! 😊

**Comment by superhighfives** [comment] 2023-12-21 17:24
Going to close this one now. 🥳

**Closed by superhighfives** 2023-12-21 17:24 UTC
Labels: bug
