### ISSUE TITLE
Feature request: Allow defining colors manually

### ISSUE THREAD

**Issue by ronilaukkarinen** [superhighfives/pika#69] opened 2021-08-06 09:11 UTC
**Is your feature request related to a problem? Please describe.**
Feature request: Allow defining hex manually when clicking the color. Now it's only possible to pick the color. Sometimes I already know the colors and it takes time to go and pick them from the screen. We should be able to input colors natively.

**Describe the solution you'd like**
When clicking the Foreground and Background, allow inputting the color. Or alternatively from the right click context menu when right clicking the color area. Or both.

**Comment by superhighfives** [comment] 2021-08-08 10:17
Thanks for flagging this issue. It looks like a duplicate of https://github.com/superhighfives/pika/issues/57, so going to close in favour of that.

**Closed by superhighfives** 2021-08-08 10:17 UTC
Labels: enhancement
