### ISSUE TITLE
Pika icon shows on top of Apple menu after restart when set to "Hide menu bar icon"

### ISSUE THREAD

**Issue by bikrrr** [superhighfives/pika#108] opened 2023-09-30 22:13 UTC
**Describe the bug**
Restarting Pika or macOS will result in the Pika menu bar icon displaying on top of the Apple menu icon in the upper-left corner of the display. 

**To Reproduce**
Prerequisites: 
**Launch at login**: Enabled
**Hide menu bar icon**: Enabled
**App Settings**: Menu bar  

1. Restart macOS -OR- quit & restart Pika
2. View the left side of the menu bar 

**Expected behavior**
No Pika menu bar icon would be visible.

**Screenshots**
![Pika Menu Bar Icon Visible](https://github.com/superhighfives/pika/assets/2607653/e168e2f5-0a34-4f49-bb08-e7a206d0b4b8)

![Pika Settings For Repro](https://github.com/superhighfives/pika/assets/2607653/51643dac-26e4-410d-b941-42c35ccde765)

**Environment (please complete the following information):**
 - OS: 14.0 (23A344) aka, Sonoma
 - App Version: 0.0.15
 - Architecture: Apple Silicon

**Additional context**
I actually saw a variation of this on Ventura, where the icon would display further down the display's left edge, but it was sporadic so I never logged it.

**Comment by jhil** [comment] 2023-10-01 22:31
Thanks everyone! I also have this issue. Also, sometimes it shows up about halfway down my screen (but still on the far left edge). Let me know if I can help with more repro details.

![Screenshot 2023-10-01 at 16 30 26](https://github.com/superhighfives/pika/assets/2228347/904f92c9-8470-4c67-a8d8-b6c581082641)

**Comment by superhighfives** [comment] 2023-10-11 13:25
Finally getting around to taking a look at this bug, and I'm struggling to reproduce it. Out of curiosity, which laptop are you using? Does it have a notch? Thanks so much for reporting!

**Comment by bikrrr** [comment] 2023-10-11 14:37
Hey, Charlie! 

I'm seeing it on a **2021 14" MacBook Pro** (has a notch) on **Sonoma 14.0 (23A344)**. It happens both on the MacBook display and when extended to an Apple Studio Display, even with the laptop in clamshell mode (closed).

**Comment by jhil** [comment] 2023-10-11 15:27
Apple M1 Max, 14 inch with notch, macos 14.0 (23A344)

**Comment by 3x3cut0r** [comment] 2023-10-12 05:56
MacMini M2, external monitor with of course no notch. macos 14.0.  
how can i get into the preferences now?

**Comment by aguilaair** [comment] 2023-10-15 05:33
M1 MBP 2021 16" on Sonoma 14.1 Beta (23B5067a)

**Comment by Sydnxt** [comment] 2023-10-15 13:07
M2 MAX MBP 2023 16" on Sonoma 14.1 Beta (23B5067a)

**Comment by nidhin-locale** [comment] 2023-10-25 17:13
I have the same issue, except mine refuse to go away even set it to show on dock.
Using 2020 m1 macbook air, with macos 14.0

<img width="745" alt="Screenshot 2023-10-25 at 22 42 24" src="https://github.com/superhighfives/pika/assets/149001481/ac6aeec8-5a80-4f88-97ed-c11726217658">

**Comment by nidhin-locale** [comment] 2023-10-31 11:23
It is possible to move the icon from the top left with "cmd + drag", but does not snap with other icons on the menu bar.

Uploading Screen Recording 2023-10-31 at 16.49.09.mp4…

**Comment by superhighfives** [comment] 2023-11-01 12:57
Really struggling to recreate this one consistently, but still looking into it. Thanks for all the context, and if there are any specific steps that consistently recreate the issue, please let me know. Also @nidhin-locale, it looks like the video you share didn't upload successfully.

**Comment by bikrrr** [comment] 2023-11-08 18:38
@superhighfives I just submitted a pull request, which (I think) fixes the issue. I tested it on both an Apple Silicon and Intel Macs and worked properly on both (no more errant Pika menubar icons). 

This is my first pull request so hopefully, I did it right?! 🤞😅

**Comment by superhighfives** [comment] 2023-11-13 09:58
Awesome, perfect PR @bikrrr—really appreciate it! 😊 Aiming to release a beta for this and Spanish localisation this week.

**Comment by superhighfives** [comment] 2023-11-13 18:54
Ah, good catch, @bikrrr! I can definitely make that change as part of 0.0.16, but if you'd like to take a pass at the PR for practice you're more than welcome. Let me know what you'd prefer.

**Comment by bikrrr** [comment] 2023-11-13 19:44
Why don't you make the change? 

I still have a lot to do on a personal project. Maybe in a while when I need a change of scenery, I can try my hand at another Pika issue!

**Comment by superhighfives** [comment] 2023-11-14 10:20
Awesome, sounds good @bikrrr. Will do. 👍

**Comment by superhighfives** [comment] 2023-11-19 22:10
This is now released as `0.0.16-beta1`, which you can access by downloading it from https://github.com/superhighfives/pika/releases/tag/0.0.16-beta1, or by checking "Subscribe to beta releases" in Pika's settings and then "Check for updates..." in the menu. Thanks @bikrrr, ya superhero!

Any feedback or issues, please let me know.

**Closed by superhighfives** 2023-11-19 22:10 UTC
Labels: bug
